name: Deploy to HuggingFace Space

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true # Ainda é bom ter para o checkout do GitHub
          fetch-depth: 0 # Evita erros de "shallow clone"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies (hf_xet, hf_hub, e do projeto)
        run: |
          pip install --upgrade pip
          # Instala as bibliotecas de deploy e as do seu projeto
          pip install huggingface_hub hf_xet
          pip install -r requirements.txt

      - name: Upload project to Hugging Face Space
        env:
          # O token é passado como variável de ambiente
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python -c "
          from huggingface_hub import HfApi
          api = HfApi()
          
          print('Uploading files to Hugging Face Space...')
          api.upload_folder(
              folder_path='.', # Envia o diretório atual
              repo_id='leo-bsb/Delivery-Time-Predictor',
              repo_type='space',
              commit_message='Sync project from GitHub Actions'
          )
          print('Upload complete.')
          "