name: Sync to Hugging Face Space

on:
  push:
    branches: [main]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout (SÓ PONTEIROS LFS)
      # Nós NÃO queremos o .pkl real ainda.
      - name: 1. Checkout do Repositório (sem LFS)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: false # <-- MUDANÇA CRÍTICA: NÃO baixa o .pkl

      # 2. Instala o Git LFS no Runner
      - name: 2. Instala o Git LFS no Runner
        run: |
          sudo apt-get update
          sudo apt-get install git-lfs
          git lfs install

      # 3. Baixa os arquivos LFS manualmente
      # Agora o runner baixa o .pkl usando o software LFS.
      # Ele sabe que é um arquivo LFS, não um binário comum.
      - name: 3. Baixa os arquivos LFS (git lfs fetch)
        run: git lfs fetch --all

      # 4. Push para o Hugging Face Space
      # Agora o 'push' tem o software LFS E o arquivo .pkl.
      # Ele fará o 'push' LFS corretamente.
      - name: 4. Push para o Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote add space https://leo-bsb:$HF_TOKEN@huggingface.co/spaces/leo-bsb/Delivery-Time-Predictor
          git push space main --force